<a href="https://colab.research.google.com/github/ziyoev-shakhrizod/Data-Science/blob/main/Boolean_indekslash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [12]:
names = np.array(['Hasan', 'Husan', 'Ilhom', 'Shaxrizod', 'Shaxriyor', 'Hasan', 'Shaxrizod'])
data = np.random.randn(7,4)

In [5]:
names

['Hasan', 'Husan', 'Ilhom', 'Shaxrizod', 'Shaxriyor', 'Hasan', 'Shaxrizod']

In [9]:
data

array([[-0.18776685, -1.34606051, -1.03560365,  0.45496894],
       [-0.13102578,  1.49247453,  1.01252293,  0.06105919],
       [-1.0182983 , -0.76000534,  1.044598  , -1.52041803],
       [-0.05029291, -0.07924336,  0.28836567, -0.69256187],
       [-1.00200672, -0.11181247, -0.38596752,  0.79360007],
       [ 1.03482281, -0.08211784, -1.03290539, -2.23615388],
       [ 0.7098099 ,  0.40438024,  0.67160164, -1.00572395]])

In [19]:
data[data<0] = 0
data

array([[0.        , 0.74365954, 1.59752709, 0.        ],
       [0.1128052 , 0.        , 0.34096379, 0.        ],
       [1.09407783, 0.        , 0.        , 0.        ],
       [0.84729396, 0.        , 0.67094637, 0.        ],
       [0.        , 2.56753396, 0.        , 1.61590299],
       [0.01099255, 1.86252015, 0.        , 0.        ],
       [0.        , 0.        , 0.18213063, 0.        ]])

In [30]:
data[names == "Shaxrizod"]

array([[0.84729396, 0.        , 0.67094637, 0.        ],
       [0.        , 0.        , 0.18213063, 0.        ]])

In [29]:
names == 'Shaxrizod'

array([False, False, False,  True, False, False,  True])

In [31]:
data[names != 'Shaxrizod]']

array([[0.        , 0.74365954, 1.59752709, 0.        ],
       [0.1128052 , 0.        , 0.34096379, 0.        ],
       [1.09407783, 0.        , 0.        , 0.        ],
       [0.84729396, 0.        , 0.67094637, 0.        ],
       [0.        , 2.56753396, 0.        , 1.61590299],
       [0.01099255, 1.86252015, 0.        , 0.        ],
       [0.        , 0.        , 0.18213063, 0.        ]])

In [32]:
#teng emasni yana bitta yo'li bor
data[~(names == "Shaxrizod")]

array([[0.        , 0.74365954, 1.59752709, 0.        ],
       [0.1128052 , 0.        , 0.34096379, 0.        ],
       [1.09407783, 0.        , 0.        , 0.        ],
       [0.        , 2.56753396, 0.        , 1.61590299],
       [0.01099255, 1.86252015, 0.        , 0.        ]])

In [33]:
#Birdaniga 2 yoki undan ko'p ma'lumot bilan ishlash uchun
mask = (names == 'Shaxrizod') | (names == 'Hasan')

In [18]:
data[mask]

array([[-0.40506609,  0.74365954,  1.59752709, -0.81888463],
       [ 0.84729396, -0.13280368,  0.67094637, -2.69617533],
       [ 0.01099255,  1.86252015, -0.07009828, -1.04148025],
       [-1.0131615 , -0.2167205 ,  0.18213063, -0.61668181]])

In [28]:
data[names == 'Hasan', 2:]

array([[1.59752709, 0.        ],
       [0.        , 0.        ]])

In [26]:
data[names == 'Hasan']


array([[0.        , 0.74365954, 1.59752709, 0.        ],
       [0.01099255, 1.86252015, 0.        , 0.        ]])