<a href="https://colab.research.google.com/github/ziyoev-shakhrizod/Data-Science/blob/main/mohirdev_amaliyot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [4]:
ar1 = np.array(1)

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [8]:
arr2 = np.zeros(9)
arr2

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [15]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [18]:
vektor = np.zeros(12)
vektor[6] = 1
vektor

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [21]:
vk = np.arange(20,60)
vk

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [26]:
rvk = np.flip(vk)
rvk

array([59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43,
       42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,
       25, 24, 23, 22, 21, 20])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [28]:
arr4 = np.arange(12,21).reshape(3,3)
arr4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [34]:
arr5 = np.array([3,7,0,0,9,0])
mtrx = np.nonzero(arr5)[0]
mtrx

array([0, 1, 4])

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [36]:
arr6 = np.random.random((2,2,2))
arr6

array([[[0.09839475, 0.15902967],
        [0.26531774, 0.59258612]],

       [[0.57003174, 0.61109141],
        [0.87078554, 0.05002186]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [40]:
arr7 = np.random.random((9,9))
arr7
#np.min(arr7)
#np.max(arr7)

array([[0.2342494 , 0.63118241, 0.5934822 , 0.15015708, 0.03329651,
        0.23723971, 0.92038377, 0.14017847, 0.87550915],
       [0.76528321, 0.53176128, 0.25756613, 0.71684755, 0.45050432,
        0.98416722, 0.38733792, 0.82747139, 0.64220493],
       [0.70296312, 0.96576774, 0.52596523, 0.74467451, 0.54951395,
        0.46800747, 0.80814409, 0.56560153, 0.83332139],
       [0.09157473, 0.44955802, 0.65672878, 0.39076379, 0.65364916,
        0.30083627, 0.35520354, 0.96689642, 0.71205559],
       [0.15608009, 0.06397294, 0.97310766, 0.3822041 , 0.15428819,
        0.53312561, 0.31534811, 0.81189393, 0.12638525],
       [0.52785242, 0.30945749, 0.16810309, 0.94558213, 0.69875675,
        0.72149564, 0.53336254, 0.25493929, 0.66745032],
       [0.94128999, 0.98227029, 0.36858488, 0.44756195, 0.90117764,
        0.43947938, 0.42976191, 0.45540884, 0.6669713 ],
       [0.99701027, 0.63747173, 0.23316993, 0.75031736, 0.7098162 ,
        0.60735124, 0.59385754, 0.50808658, 0.77636458],


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [42]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
nan
False
False
nan
True
True


NameError: name 'nan' is not defined

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [46]:
mtrx1 = np.ones((6,3))
mtrx2 = np.ones((3,4))
res = np.dot(mtrx1, mtrx2)
res

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [47]:
from numpy import *
print(sum(range(5),-1))

10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [48]:
import numpy as np

# Ikki massivni yaratish
a = np.array([1, 2])
b = np.array([4, 5])

# Solishtirish amallarni bajaramiz
print("Array a:", a)
print("Array b:", b)
print("a > b")
print(a > b)
print("a >= b")
print(a >= b)
print("a < b")
print(a < b)
print("a <= b")
print(a <= b)


Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [49]:
nan
inf
[nan]


[nan]

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [50]:
ar1 = np.array([1,2,3,4,5])
ar2 = np.array([3,4,5,6,7])
result = np.intersect1d(ar1,ar2)
result

array([3, 4, 5])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [54]:
ar3 = np.random.random(10)
mis1 = ar3[ar3>0]%1
mis2 = np.floor(ar3[ar3>0])
mis3 = ar3[ar3>0].astype(int)
mis4 = np.trunc(ar3[ar3>0])
mis1

array([0.77478487, 0.43982391, 0.25073317, 0.49165205, 0.37929497,
       0.14627368, 0.22717671, 0.66584716, 0.84559952, 0.25815014])

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [58]:
ar4 = np.arange(9).reshape(3,3)
ar4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [61]:
vek = np.random.randn(10)
sorted_vek = np.sort(vek)
butun = np.abs(sorted_vek)
butun

array([1.63363786, 1.4308706 , 1.13259381, 0.85622605, 0.6580886 ,
       0.62595148, 0.2573747 , 0.83217816, 1.07733354, 1.18240903])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [63]:
a = np.random.randn(5)
b = np.random.randn(5)
#resl = np.allclose(a,b)
resl = np.array_equal(a,b)
resl

False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [72]:
mt1 = np.arange(1,19).reshape(6,3)
mt2 = np.arange(11,23).reshape(3,4)
mtm = np.dot(mt1,mt2)
#mtm = np.ones(mt1,mt2)
mtm

array([[ 98, 104, 110, 116],
       [233, 248, 263, 278],
       [368, 392, 416, 440],
       [503, 536, 569, 602],
       [638, 680, 722, 764],
       [773, 824, 875, 926]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [77]:
mt3 = np.random.randn(5)
katta = np.argmax(mt3)
mt3[katta] = 0
mt3

array([ 0.57405585, -0.80259001, -0.05238379,  1.6263373 ,  0.        ])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [93]:
bugun = np.datetime64('today', 'D')
ertaga = np.datetime64('today', 'D') + np.timedelta64(1, "D")
kecha = datetime64('today', 'D') - np.timedelta64(1, 'D')
print(f"Kechangi sana : {kecha}")
print(f"Bugungi sana : {bugun}")
print(f"Ertangi sana : {ertaga}")

Kechangi sana : 2024-05-11
Bugungi sana : 2024-05-12
Ertangi sana : 2024-05-13


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [94]:
sanalar = np.arange('2016-01', '2016-02', dtype='datetime64[D]')
sanalar

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [95]:
import numpy as np

# Tasodifiy massiv yaratish
arr = np.random.randn(10) * 10

# Butun son qismini ajratib olish usullari
method1 = arr[arr > 0] % 1
method2 = np.floor(arr[arr > 0])
method3 = arr[arr > 0].astype(int)
method4 = np.trunc(arr[arr > 0])

# Natijalarni ekranga chiqarish
print("Method 1 (remainder with %):", method1)
print("Method 2 (floor):", method2)
print("Method 3 (astype):", method3)
print("Method 4 (trunc):", method4)


Method 1 (remainder with %): [0.0148593  0.00680807 0.55130743 0.74446822 0.18315838 0.60522791]
Method 2 (floor): [ 0.  1. 15.  9.  2. 10.]
Method 3 (astype): [ 0  1 15  9  2 10]
Method 4 (trunc): [ 0.  1. 15.  9.  2. 10.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [97]:
son = np.random.randn(10000)
results = np.add.reduce(son)
results

106.04947380551296

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [110]:
#Berilgan vektor
vector = np.array([1, 2, 3, 4, 5])
new_vector = np.zeros(len(vector) + len(vector) - 1, dtype=int)
new_vector

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [111]:
from numpy.lib.stride_tricks import as_strided

# Berilgan massiv
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

# a massivining o'lchami
n = len(a)

# b massivining o'lchami
m = 4

# b massivini yaratish
b = as_strided(a, shape=(n-m+1, m), strides=(a.itemsize, a.itemsize))

print(b)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [112]:
array = np.random.randint(0,10, size=20)
array1 = np.bincount(array)
array2 = np.argmax(array1)
array2


7

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`